name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ make nlohmann-json3-dev qt6-base-dev

      - name: Build core and DUKE
        run: |
          make -C core
          make -C third_party/DUKE

      - name: Test
        run: |
          make -C tests
          ./tests/run_tests
