---
name: CI

'on':
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ make nlohmann-json3-dev qt6-base-dev
          pkg-config --modversion Qt6Core

      - name: Build core
        run: make -C core

      - name: Test
        run: |
          cd third_party/DUKE
          make -C tests
          ./tests/run_tests
